services:
  airflow-scheduler:
    image: us.gcr.io/galoyorg/meltano@sha256:5225338eee4c283c917cb64b892baa457fd1dcfa9e929cb10b071bd823730c83
    # image: meltano:latest # nix build .#meltano-image && docker load < result
    command: meltano invoke airflow scheduler
    volumes:
      - "meltano-metadata:/workspace/meltano/.meltano:rw"
      - "./meltano:/meltano:ro"
      - "./meltano/keyfile.json:/workspace/meltano/keyfile.json:ro"
    healthcheck:
      test: ["CMD", "airflow-scheduler-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      airflow-pg: { condition: service_healthy }
      core-pg: { condition: service_started }
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@airflow-pg:5432/pg
      TAP_POSTGRES_HOST: core-pg
      TAP_POSTGRES_PORT: 5432
      TARGET_BIGQUERY_CREDENTIALS_JSON: ${TARGET_BIGQUERY_CREDENTIALS_JSON}
      TARGET_BIGQUERY_DATASET: ${TARGET_BIGQUERY_DATASET}
      DBT_BIGQUERY_DATASET: ${DBT_BIGQUERY_DATASET}
      DBT_BIGQUERY_PROJECT: ${DBT_BIGQUERY_PROJECT}
      DOCS_BUCKET_NAME: ${DOCS_BUCKET_NAME}
      SUMSUB_KEY: ${SUMSUB_KEY}
      SUMSUB_SECRET: ${SUMSUB_SECRET}

  airflow-webserver:
    image: us.gcr.io/galoyorg/meltano@sha256:5225338eee4c283c917cb64b892baa457fd1dcfa9e929cb10b071bd823730c83
    # image: meltano:latest # nix build .#meltano-image && docker load < result
    command: meltano invoke airflow webserver
    ports: [8080:8080]
    volumes:
      - "meltano-metadata:/workspace/meltano/.meltano:rw"
      - "./meltano:/meltano:ro"
      - "./meltano/keyfile.json:/workspace/meltano/keyfile.json:ro"
    depends_on: 
      airflow-pg: { condition: service_healthy }
      airflow-scheduler: { condition: service_healthy }
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@airflow-pg:5432/pg

  airflow-pg:
    image: ghcr.io/cloudnative-pg/postgresql:17.5
    ports: [5436:5432]
    environment:
      [POSTGRES_USER=user, POSTGRES_PASSWORD=password, POSTGRES_DB=pg]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pg"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  meltano-metadata: {} # Meltano shared caching layer
