mutation ChartOfAccountsAddNode($input: ChartOfAccountsAddNodeInput) {
  chartOfAccountsAddNode(input: $input) {
    chartOfAccounts {
      chartId
      name
      children {
        ...child
        children {
          ...child
          children {
          ...child
            children {
              ...child
            }
          }
        }
      }
    }
  }
}

fragment child on ChartNode {
  name
  accountCode
}
