query CustomerAuditLog($id: UUID!) {
  customer(id: $id) {
    customerId
  }
  audit(first: 100, after: null) {
    nodes {
      subject {
        ... on User {
          userId
          email
          role {
            name
          }
        }
        ... on System {
          name
        }
      }
      object
      action
      authorized
      recordedAt
    }
  }
}
